### ISSUE TITLE
impossible to npm start

### ISSUE THREAD

**Issue by zoomclub** [Flipboard/react-canvas#19]
After a npm install I'm not able to start react-canvas. Below is the terminal output in webstorm and the contents of the npm-debug.log:

SM@SM-MacBook-Pro ~/D/p/x/v/react-canvas> npm start

> react-canvas@0.0.1 start /Users/SM/Desktop/projects/x5-apex-PROJECTS/varia-SURFACE/react-canvas
> gulp

[08:20:38] Using gulpfile ~/Desktop/projects/x5-apex-PROJECTS/varia-SURFACE/react-canvas/gulpfile.js
[08:20:38] Starting 'clean'...
[08:20:38] Finished 'clean' after 3.38 ms
[08:20:38] Starting 'build'...
[08:20:39] Starting 'serve'...
[08:20:40] Finished 'serve' after 245 ms
[08:20:40] Starting 'watch'...
[08:20:40] Finished 'watch' after 7 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at ConnectApp.server (/Users/SM/Desktop/projects/x5-apex-PROJECTS/varia-SURFACE/react-canvas/node_modules/gulp-connect/index.js:57:19)
    at new ConnectApp (/Users/SM/Desktop/projects/x5-apex-PROJECTS/varia-SURFACE/react-canvas/node_modules/gulp-connect/index.js:37:10)
    at Object.module.exports.server (/Users/SM/Desktop/projects/x5-apex-PROJECTS/varia-SURFACE/react-canvas/node_modules/gulp-connect/index.js:170:12)
    at Gulp.<anonymous> (/Users/SM/Desktop/projects/x5-apex-PROJECTS/varia-SURFACE/react-canvas/gulpfile.js:18:11)
    at module.exports (/Users/SM/Desktop/projects/x5-apex-PROJECTS/varia-SURFACE/react-canvas/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/SM/Desktop/projects/x5-apex-PROJECTS/varia-SURFACE/react-canvas/node_modules/gulp/node_modules/orchestrator/index.js:273:3)

npm ERR! Darwin 11.4.2
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.7
npm ERR! code ELIFECYCLE
npm ERR! react-canvas@0.0.1 start: `gulp`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the react-canvas@0.0.1 start script.
npm ERR! This is most likely a problem with the react-canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/SM/Desktop/projects/x5-apex-PROJECTS/varia-SURFACE/react-canvas/npm-debug.log

Here is the npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.1.7
3 info using node@v0.10.33
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart react-canvas@0.0.1
6 info start react-canvas@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info react-canvas@0.0.1 Failed to exec start script
9 verbose stack Error: react-canvas@0.0.1 start: `gulp`
9 verbose stack Exit status 8
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
9 verbose stack     at ChildProcess.emit (events.js:98:17)
9 verbose stack     at maybeClose (child_process.js:756:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
10 verbose pkgid react-canvas@0.0.1
11 verbose cwd /Users/SM/Desktop/projects/x5-apex-PROJECTS/varia-SURFACE/react-canvas
12 error Darwin 11.4.2
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.10.33
15 error npm  v2.1.7
16 error code ELIFECYCLE
17 error react-canvas@0.0.1 start: `gulp`
17 error Exit status 8
18 error Failed at the react-canvas@0.0.1 start script.
18 error This is most likely a problem with the react-canvas package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp
18 error You can get their info via:
18 error     npm owner ls react-canvas
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by mjohnston** [comment]
You likely have another server listening on port 8080, or another live reload server on 35729.

I've added the option to override the server and live reload ports, as this is a pretty common use case. For instance:
```
PORT=3000 RELOAD_PORT=35868 npm start
```

**Comment by zoomclub** [comment]
Thanks, looking good!
