### ISSUE TITLE
cannot run examples

### ISSUE THREAD

**Issue by deadlyicon** [Flipboard/react-canvas#54]
```sh
☃ npm start

> react-canvas@0.0.1 start /Users/deadlyicon/tmp/react-canvas
> gulp

[16:03:07] Using gulpfile ~/tmp/react-canvas/gulpfile.js
[16:03:07] Starting 'clean'...
[16:03:07] Finished 'clean' after 2.42 ms
[16:03:07] Starting 'build'...
[16:03:07] Starting 'serve'...
[16:03:07] Finished 'serve' after 7.43 ms
[16:03:07] Starting 'watch'...
[16:03:07] Finished 'watch' after 4.16 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at ConnectApp.server (/Users/deadlyicon/tmp/react-canvas/node_modules/gulp-connect/index.js:57:19)
    at new ConnectApp (/Users/deadlyicon/tmp/react-canvas/node_modules/gulp-connect/index.js:37:10)
    at Object.module.exports.server (/Users/deadlyicon/tmp/react-canvas/node_modules/gulp-connect/index.js:170:12)
    at Gulp.<anonymous> (/Users/deadlyicon/tmp/react-canvas/gulpfile.js:21:11)
    at module.exports (/Users/deadlyicon/tmp/react-canvas/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/deadlyicon/tmp/react-canvas/node_modules/gulp/node_modules/orchestrator/index.js:273:3)

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.11
npm ERR! code ELIFECYCLE
npm ERR! react-canvas@0.0.1 start: `gulp`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the react-canvas@0.0.1 start script 'gulp'.
npm ERR! This is most likely a problem with the react-canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/deadlyicon/tmp/react-canvas/npm-debug.log
```

npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.1.11
3 info using node@v0.10.33
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart react-canvas@0.0.1
7 info start react-canvas@0.0.1
8 verbose unsafe-perm in lifecycle true
9 info react-canvas@0.0.1 Failed to exec start script
10 verbose stack Error: react-canvas@0.0.1 start: `gulp`
10 verbose stack Exit status 8
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
10 verbose stack     at EventEmitter.emit (events.js:98:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:98:17)
10 verbose stack     at maybeClose (child_process.js:756:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
11 verbose pkgid react-canvas@0.0.1
12 verbose cwd /Users/deadlyicon/tmp/react-canvas
13 error Darwin 14.1.0
14 error argv "node" "/usr/local/bin/npm" "start"
15 error node v0.10.33
16 error npm  v2.1.11
17 error code ELIFECYCLE
18 error react-canvas@0.0.1 start: `gulp`
18 error Exit status 8
19 error Failed at the react-canvas@0.0.1 start script 'gulp'.
19 error This is most likely a problem with the react-canvas package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     gulp
19 error You can get their info via:
19 error     npm owner ls react-canvas
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by mjohnston** [comment]
This means you have another server listening on port 8080. You can either kill that server, or use another server to run the examples:
```
PORT=3000 npm start
```
